### ISSUE TITLE
Updating to JoyPixels 6.6

### ISSUE THREAD

**Issue by kjlawrencelaw** [shivangswain/JoyPixels#4]
There is latest update, 6.6 recently, so would you mind update' to the latest version

Thx in advance

**Comment by shivangswain** [comment]
No problem, I'll get on it as soon as I come back from uni. Thanks for letting me know.

**Comment by shivangswain** [comment]
The update has been released. You can find the latest module zip in the Releases section. Thanks for bringing this to my attention and sorry for the delay. Cheers!
