### ISSUE TITLE
Updating to JoyPixels 7.0

### ISSUE THREAD

**Issue by OmarRol-1** [shivangswain/JoyPixels#8]
Will update to version 7.0

**Comment by k4ustu3h** [comment]
But JoyPixels still haven't released the latest version as a free font, like they did for 6.6. So it's not possible yet. 

https://joypixels.com/download

**Comment by shivangswain** [comment]
We now have the font available as a free download. I will be updating the module by EOD.

**Comment by shivangswain** [comment]
The new update has been released. The font file had to be sourced from this [JoyPixels Tweet](https://twitter.com/joypixels/status/1554245168131215360) as they are yet to release it on their website.
