### ISSUE TITLE
8.0 

### ISSUE THREAD

**Issue by OmarRol-1** [shivangswain/JoyPixels#9]
You plan support for version 8.0

**Comment by shivangswain** [comment]
I have switched to an iPhone and do not own an Android device to test this at the moment. I can maybe just update the font files and make a pre-release version but I cannot test it or guarantee it would work with newer Android versions and Magisk implementations.

**Comment by shivangswain** [comment]
Also, JoyPixels and gone ahead and done [this](https://joypixels.com/fonts) to Android fonts so consider JoyPixels® 7.0 the last free (debatable) version of JoyPixels for Android:

<img width="1005" alt="image" src="https://github.com/shivangswain/joypixels/assets/33395916/99e077b8-7865-48be-bf1d-6bdc73acea3a">

**Comment by eXtrem0us** [comment]
@OmarRol-1 I made a fork. Check it out: https://github.com/eXtrem0us/joypixels

**Comment by TeaqariaWTF** [comment]
> @OmarRol-1 I made a fork. Check it out: https://github.com/eXtrem0us/joypixels

Android 14 does not work on kernelsu
